name: Run Python Tests on Windows

on:
  push:
    branches:
      - main  # Runs tests on push to main branch (modify as needed)
  pull_request:
    branches:
      - main  # Runs tests on pull requests to main

jobs:
  test:
    runs-on: windows-latest  # Runs on a Windows machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your repo code into the workflow

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"
        shell: pwsh  # Use PowerShell (needed for Windows compatibility)

      - name: Run tests
        run: pytest tests/
        shell: pwsh  # Ensure PowerShell is used to execute the command
