name: Run Python Tests

on:
  push:
    branches:
      - main  # Runs tests on push to main branch (modify as needed)
  pull_request:
    branches:
      - main  # Runs tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on an Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your repo code into the workflow

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run tests
        run: pytest  # Runs pytest (ensure you have test files)
